name: Docker Image Scan

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t scan-target:${{ inputs.tag }} .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: scan-target:${{ inputs.tag }}
          format: table
          output: trivy-report.txt
          severity: CRITICAL,HIGH
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Display Trivy Report
        if: always()
        run: |
          cat trivy-report.txt

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt